### ISSUE TITLE
[Bug] IconClassToClose or IconClassToOpen not specified

### ISSUE THREAD

**Issue by wartek69** [Blazored/Menu#31]
**Describe the bug**
I'm getting the following while trying to use a submenu.
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: IconClassToClose or IconClassToOpen not specified
System.ArgumentException: IconClassToClose or IconClassToOpen not specified
   at Blazored.Menu.BlazoredSubMenuBase.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```
I just followed the readme to import the library in a .net7 app using webassembly.

**Comment by Otto404** [comment]
I see that error as well

**Comment by SteveTeece** [comment]
I'm getting it targeting .net6 in a Blazor Server app
